### ISSUE TITLE
[meta] investigate Tkrzw for KV store

### ISSUE THREAD

**Issue by indrora** [LumoSQL/lumosql#5]
Previously, a project to produce highly scalable DBM key value stores was backed by a social network. 

Tokyo Cabinet and later Kyoto Cabinet handle dynamic, shared databases up to 8 EiB. These were left without much funding and were somewhat left abandoned. 

The author behind them however has been working on a follow up called [Tkrzw](https://dbmx.net/tkrzw/), which has many of the features. 

Pros: 
* Multiple implementations of key-value stores that have different tradeoffs for different needs. 
* Apache2 licensed
* clean API

Issues: 
* Written in C++, not ANSI C as SQLite is.
* maintained by one person.

**Comment by danshearer** [comment]
Many thanks for the suggestion. These days this is really quite realistic to do with LumoSQL, and while we still don't quite have a clean API yet the aspect of C vs C++ would be much less difficult than if the K-V APIs were a bad match. I have emailed Mikio Hirabayashi to see what he might think.

Dan
